### ISSUE TITLE
Suggestion List

### ISSUE THREAD

**Issue by MagnusHellstrom** [Dandelion1608/VoltzTekk-Reborn#1]
Almost Unified
Works well with Polymorph.
https://modrinth.com/mod/almost-unified

RightClickHarvest
You mentioned wanting it.
https://modrinth.com/mod/rightclickharvest

Create Big Cannons
I'd like howitzers to match Garth's missiles.
https://modrinth.com/mod/create-big-cannons

Embers: Rekindled
A pretty cool, dwarven-esque magitech mod.
https://modrinth.com/mod/embers

The Aether: Redux
An addon for the Aether mod. Good reviews.
https://modrinth.com/mod/the-aether-redux

Upgrade Aquatic
Adds some good underwater content, like those sonar sharks we had before.
Already checked the license, we're good to distribute.
https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic

Ars Noveau and the addons you have appear to be on Modrinth now. Probably a good idea to just grab them rather than importing an override.

**Comment by Dandelion1608** [comment]
Upgrade Aquatic has a clause in its License Denying the right to redistribute - Permission to include in modpacks is likely overuled by the distribution clause, all others are being added in next update
