### ISSUE TITLE
Gravestone Deletion

### ISSUE THREAD

**Issue by Garthok2962** [Dandelion1608/VoltzTekk-Reborn#7]
Dying by dragon deletes your Gravestone at times

**Comment by Dandelion1608** [comment]
I'll need you to provide the Obituary Death ID found by pressing F3+H, opening your Inventory and opening the Obituary - the ID will copy to clipboard on Click so you can paste it without trying to squint and type out the ID
[More Info](https://github.com/Dandelion1608/VoltzTekk-Reborn/issues/8)

**Comment by Dandelion1608** [comment]
Inventory Restored
